# Generated by Django 4.1 on 2023-12-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_censusgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
