# Generated by Django 4.1 on 2023-12-19 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_questionoption_preference_voting_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='preferences',
            field=models.CharField(default='[0, 0, 0]', max_length=100, validators=[django.core.validators.int_list_validator]),
        ),
    ]
